# Generated by Django 6.1.1 on 2026-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(default='default_text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.TextField(default='display_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(default='profile_image_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
