# Generated by Django 6.1.1 on 2026-10-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_photo_image_file_alter_photo_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='posts',
            new_name='post',
        ),
    ]
